/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyingIndexRouteImport } from './routes/studying.index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as StudyingGradeRouteImport } from './routes/studying.$grade'
import { Route as AuthenticatedStudyingRouteImport } from './routes/_authenticated/studying'
import { Route as AuthenticatedLoungeRouteImport } from './routes/_authenticated/lounge'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedExamRouteImport } from './routes/_authenticated/exam'
import { Route as StudyingGradeIndexRouteImport } from './routes/studying.$grade.index'
import { Route as StudyingGradeSubjectRouteImport } from './routes/studying.$grade.$subject'
import { Route as StudyingGradeSubjectIndexRouteImport } from './routes/studying.$grade.$subject.index'
import { Route as StudyingGradeSubjectQuizUnitRouteImport } from './routes/studying.$grade.$subject.quiz.$unit'
import { Route as StudyingGradeSubjectReadingUnitSubRouteImport } from './routes/studying.$grade.$subject.reading.$unit.$sub'

const StudyingIndexRoute = StudyingIndexRouteImport.update({
  id: '/studying/',
  path: '/studying/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyingGradeRoute = StudyingGradeRouteImport.update({
  id: '/studying/$grade',
  path: '/studying/$grade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudyingRoute = AuthenticatedStudyingRouteImport.update({
  id: '/_authenticated/studying',
  path: '/studying',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLoungeRoute = AuthenticatedLoungeRouteImport.update({
  id: '/_authenticated/lounge',
  path: '/lounge',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/_authenticated/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedExamRoute = AuthenticatedExamRouteImport.update({
  id: '/_authenticated/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyingGradeIndexRoute = StudyingGradeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudyingGradeRoute,
} as any)
const StudyingGradeSubjectRoute = StudyingGradeSubjectRouteImport.update({
  id: '/$subject',
  path: '/$subject',
  getParentRoute: () => StudyingGradeRoute,
} as any)
const StudyingGradeSubjectIndexRoute =
  StudyingGradeSubjectIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudyingGradeSubjectRoute,
  } as any)
const StudyingGradeSubjectQuizUnitRoute =
  StudyingGradeSubjectQuizUnitRouteImport.update({
    id: '/quiz/$unit',
    path: '/quiz/$unit',
    getParentRoute: () => StudyingGradeSubjectRoute,
  } as any)
const StudyingGradeSubjectReadingUnitSubRoute =
  StudyingGradeSubjectReadingUnitSubRouteImport.update({
    id: '/reading/$unit/$sub',
    path: '/reading/$unit/$sub',
    getParentRoute: () => StudyingGradeSubjectRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/exam': typeof AuthenticatedExamRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/lounge': typeof AuthenticatedLoungeRoute
  '/studying': typeof AuthenticatedStudyingRoute
  '/studying/$grade': typeof StudyingGradeRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/studying/': typeof StudyingIndexRoute
  '/studying/$grade/$subject': typeof StudyingGradeSubjectRouteWithChildren
  '/studying/$grade/': typeof StudyingGradeIndexRoute
  '/studying/$grade/$subject/': typeof StudyingGradeSubjectIndexRoute
  '/studying/$grade/$subject/quiz/$unit': typeof StudyingGradeSubjectQuizUnitRoute
  '/studying/$grade/$subject/reading/$unit/$sub': typeof StudyingGradeSubjectReadingUnitSubRoute
}
export interface FileRoutesByTo {
  '/exam': typeof AuthenticatedExamRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/lounge': typeof AuthenticatedLoungeRoute
  '/studying': typeof StudyingIndexRoute
  '/': typeof AuthenticatedIndexRoute
  '/studying/$grade': typeof StudyingGradeIndexRoute
  '/studying/$grade/$subject': typeof StudyingGradeSubjectIndexRoute
  '/studying/$grade/$subject/quiz/$unit': typeof StudyingGradeSubjectQuizUnitRoute
  '/studying/$grade/$subject/reading/$unit/$sub': typeof StudyingGradeSubjectReadingUnitSubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/exam': typeof AuthenticatedExamRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/lounge': typeof AuthenticatedLoungeRoute
  '/_authenticated/studying': typeof AuthenticatedStudyingRoute
  '/studying/$grade': typeof StudyingGradeRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/studying/': typeof StudyingIndexRoute
  '/studying/$grade/$subject': typeof StudyingGradeSubjectRouteWithChildren
  '/studying/$grade/': typeof StudyingGradeIndexRoute
  '/studying/$grade/$subject/': typeof StudyingGradeSubjectIndexRoute
  '/studying/$grade/$subject/quiz/$unit': typeof StudyingGradeSubjectQuizUnitRoute
  '/studying/$grade/$subject/reading/$unit/$sub': typeof StudyingGradeSubjectReadingUnitSubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/exam'
    | '/leaderboard'
    | '/lounge'
    | '/studying'
    | '/studying/$grade'
    | '/'
    | '/studying/'
    | '/studying/$grade/$subject'
    | '/studying/$grade/'
    | '/studying/$grade/$subject/'
    | '/studying/$grade/$subject/quiz/$unit'
    | '/studying/$grade/$subject/reading/$unit/$sub'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/exam'
    | '/leaderboard'
    | '/lounge'
    | '/studying'
    | '/'
    | '/studying/$grade'
    | '/studying/$grade/$subject'
    | '/studying/$grade/$subject/quiz/$unit'
    | '/studying/$grade/$subject/reading/$unit/$sub'
  id:
    | '__root__'
    | '/_authenticated/exam'
    | '/_authenticated/leaderboard'
    | '/_authenticated/lounge'
    | '/_authenticated/studying'
    | '/studying/$grade'
    | '/_authenticated/'
    | '/studying/'
    | '/studying/$grade/$subject'
    | '/studying/$grade/'
    | '/studying/$grade/$subject/'
    | '/studying/$grade/$subject/quiz/$unit'
    | '/studying/$grade/$subject/reading/$unit/$sub'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedExamRoute: typeof AuthenticatedExamRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedLoungeRoute: typeof AuthenticatedLoungeRoute
  AuthenticatedStudyingRoute: typeof AuthenticatedStudyingRoute
  StudyingGradeRoute: typeof StudyingGradeRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  StudyingIndexRoute: typeof StudyingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studying/': {
      id: '/studying/'
      path: '/studying'
      fullPath: '/studying/'
      preLoaderRoute: typeof StudyingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studying/$grade': {
      id: '/studying/$grade'
      path: '/studying/$grade'
      fullPath: '/studying/$grade'
      preLoaderRoute: typeof StudyingGradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studying': {
      id: '/_authenticated/studying'
      path: '/studying'
      fullPath: '/studying'
      preLoaderRoute: typeof AuthenticatedStudyingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/lounge': {
      id: '/_authenticated/lounge'
      path: '/lounge'
      fullPath: '/lounge'
      preLoaderRoute: typeof AuthenticatedLoungeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/exam': {
      id: '/_authenticated/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof AuthenticatedExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studying/$grade/': {
      id: '/studying/$grade/'
      path: '/'
      fullPath: '/studying/$grade/'
      preLoaderRoute: typeof StudyingGradeIndexRouteImport
      parentRoute: typeof StudyingGradeRoute
    }
    '/studying/$grade/$subject': {
      id: '/studying/$grade/$subject'
      path: '/$subject'
      fullPath: '/studying/$grade/$subject'
      preLoaderRoute: typeof StudyingGradeSubjectRouteImport
      parentRoute: typeof StudyingGradeRoute
    }
    '/studying/$grade/$subject/': {
      id: '/studying/$grade/$subject/'
      path: '/'
      fullPath: '/studying/$grade/$subject/'
      preLoaderRoute: typeof StudyingGradeSubjectIndexRouteImport
      parentRoute: typeof StudyingGradeSubjectRoute
    }
    '/studying/$grade/$subject/quiz/$unit': {
      id: '/studying/$grade/$subject/quiz/$unit'
      path: '/quiz/$unit'
      fullPath: '/studying/$grade/$subject/quiz/$unit'
      preLoaderRoute: typeof StudyingGradeSubjectQuizUnitRouteImport
      parentRoute: typeof StudyingGradeSubjectRoute
    }
    '/studying/$grade/$subject/reading/$unit/$sub': {
      id: '/studying/$grade/$subject/reading/$unit/$sub'
      path: '/reading/$unit/$sub'
      fullPath: '/studying/$grade/$subject/reading/$unit/$sub'
      preLoaderRoute: typeof StudyingGradeSubjectReadingUnitSubRouteImport
      parentRoute: typeof StudyingGradeSubjectRoute
    }
  }
}

interface StudyingGradeSubjectRouteChildren {
  StudyingGradeSubjectIndexRoute: typeof StudyingGradeSubjectIndexRoute
  StudyingGradeSubjectQuizUnitRoute: typeof StudyingGradeSubjectQuizUnitRoute
  StudyingGradeSubjectReadingUnitSubRoute: typeof StudyingGradeSubjectReadingUnitSubRoute
}

const StudyingGradeSubjectRouteChildren: StudyingGradeSubjectRouteChildren = {
  StudyingGradeSubjectIndexRoute: StudyingGradeSubjectIndexRoute,
  StudyingGradeSubjectQuizUnitRoute: StudyingGradeSubjectQuizUnitRoute,
  StudyingGradeSubjectReadingUnitSubRoute:
    StudyingGradeSubjectReadingUnitSubRoute,
}

const StudyingGradeSubjectRouteWithChildren =
  StudyingGradeSubjectRoute._addFileChildren(StudyingGradeSubjectRouteChildren)

interface StudyingGradeRouteChildren {
  StudyingGradeSubjectRoute: typeof StudyingGradeSubjectRouteWithChildren
  StudyingGradeIndexRoute: typeof StudyingGradeIndexRoute
}

const StudyingGradeRouteChildren: StudyingGradeRouteChildren = {
  StudyingGradeSubjectRoute: StudyingGradeSubjectRouteWithChildren,
  StudyingGradeIndexRoute: StudyingGradeIndexRoute,
}

const StudyingGradeRouteWithChildren = StudyingGradeRoute._addFileChildren(
  StudyingGradeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedExamRoute: AuthenticatedExamRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedLoungeRoute: AuthenticatedLoungeRoute,
  AuthenticatedStudyingRoute: AuthenticatedStudyingRoute,
  StudyingGradeRoute: StudyingGradeRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  StudyingIndexRoute: StudyingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
